apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngnix # label that it select
spec:
  replicas: {{.Values.scale}}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx: {{.Values.tag}}
          ports:
            - containerPort: 80